name: ci

on:
  pull_request:
  push:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v2.4.0

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v2.1.5
        with:
          go-version: '1.21'
          check-latest: true

      - name: build
        run: |
          make apko
          ./apko version

      - name: Setup cosign (needed in CI tests)
        uses: sigstore/cosign-installer@11086d25041f77fe8fe7b9ea4e48e3b9192b8f19 # v3.1.2

      - name: Setup crane (needed in CI tests)
        uses: imjasonh/setup-crane@00c9e93efa4e1138c9a7a5c594acd6c75a2fbf0c # v0.3

      - name: Run CI tests in hack/ci/
        run: |
          make ci

      - uses: goreleaser/goreleaser-action@3fa32b8bb5620a2c1afe798654bbad59f9da4906 # v2.8.1
        with:
          version: latest
          install-only: true

      - name: snapshot
        timeout-minutes: 30
        run: |
          make snapshot
          ./dist/apko-build_linux_amd64_v1/apko version
