name: ci

on:
  pull_request:
  push:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v2.4.0

      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v2.1.5
        with:
          go-version: 1.19
          check-latest: true

      - name: build
        run: |
          make apko
          ./apko version

      - name: Setup cosign (needed in CI tests)
        uses: sigstore/cosign-installer@v3

      - name: Run CI tests in hack/ci/
        run: |
          make ci

      - uses: goreleaser/goreleaser-action@f82d6c1c344bcacabba2c841718984797f664a6b # v2.8.1
        with:
          version: latest
          install-only: true

      - name: snapshot
        run: |
          make snapshot
          ./dist/apko-build_linux_amd64_v1/apko version
