name: Go Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v3.0.0
      with:
        go-version: 1.19
        check-latest: true

    - name: Checkout code
      uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3

    - name: Test
      run: make test
